### ISSUE TITLE
2022年7月以前に登録された曲のカバー画像が表示できない

### ISSUE THREAD

**Issue by noi-jp** [hibit-at/jbsl-web#2]
## 概要
一部曲のカバー画像がリンク切れ表示となっている。
https://github.com/hibit-at/jbsl-web/commit/e0457a887bceb809bb98d4bc9a531da585a3aa14 のコミット以前に登録された曲の画像URLが404エラーとなっている模様。

OK : `https://cdn.scoresaber.com/covers/539FF34D78236DA844DE2EEABC42656F9AB615C1.png`
NG : `https://scoresaber.com/imports/images/songs/539FF34D78236DA844DE2EEABC42656F9AB615C1.png`

### サンプル
![image](https://github.com/hibit-at/jbsl-web/assets/1614574/c57775cb-528d-426c-bdad-ca8793dcdb33)

## 提案
旧URLで登録された曲のカバー画像に対して、新URLに一括置換できないか。

```sql
UPDATE Song
SET imageURL = REPLACE(imageURL, 'https://scoresaber.com/imports/images/songs/', 'https://cdn.scoresaber.com/covers/')
WHERE imageURL LIKE 'https://scoresaber.com/imports/images/songs/%';
```

**Comment by hibit-at** [comment]
ご提示いただきました方針に従って置換完了しました！ありがとうございます
